# Project: Dong Ho
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -std=c++11
CC       = gcc.exe -std=c++11
WINDRES  = windres.exe
OBJ      = DongHo.o DongHo2.o DongHo3.o
LINKOBJ  = DongHo.o DongHo2.o DongHo3.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -lbgi -lgdi32 -luser32 -m32
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = DongHo.exe
CXXFLAGS = $(CXXINCS) -m32
CFLAGS   = $(INCS) -m32
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

DongHo.o: DongHo.cpp
	$(CPP) -c DongHo.cpp -o DongHo.o $(CXXFLAGS)

DongHo2.o: DongHo2.cpp
	$(CPP) -c DongHo2.cpp -o DongHo2.o $(CXXFLAGS)

DongHo3.o: DongHo3.cpp
	$(CPP) -c DongHo3.cpp -o DongHo3.o $(CXXFLAGS)
